### PR TITLE
Fix purge type for Varnish

### PR DESCRIPTION
**Pull request by andrerom**
ref: https://github.com/ezsystems/ezplatform/pull/522
Relevant for 3.0 and up.

### CODE REVIEW

**Comment by xrow** [comment]
Do we need new ez release? I still have an error on 3.0.3

**Comment by andrerom** [comment]
@xrow What error? you did not mention any error anywhere.

**Comment by xrow** [comment]
image

**Comment by andrerom** [comment]
@xrow This PR _(like the other one you commented on as well)_ is about fixing the doc so it correctly states you should use `varnish` not `http`, did you try that?

**Comment by xrow** [comment]
I looks the env var is not being picked put. Need to look into it.

**Comment by xrow** [comment]
Hmmm... I have now this error wiht 3.0.4

You have requested a non-existent service "cache.redis".

image

**Comment by andrerom** [comment]
That seems like something rather relevant to the CACHE_DSN issue you reported separately, not so much HttpCache?

**Comment by xrow** [comment]
This is true. I just wanted to report my issues with the latest version.

**Pull request merged**
