### PR TITLE
Removed leftover `Platform` from package structure docs

### PR DESCRIPTION
**Pull request by Steveb-p**
| Question      | Answer
| ------------- | ---
| JIRA Ticket   | N/A
| Versions      | 3.3 :grey_question: / 4.0

Platforms are bad now, so I've removed the remaining platforms.

### CODE REVIEW

**Review by alongosz — APPROVED** [review]
> Platforms are bad now, so I've removed the remaining platforms.

Bad platform, go to the corner :rofl:

**Review by DominikaK — APPROVED** [review]

**Comment by DominikaK** [comment]
@alongosz @Steveb-p, so is this 3.3 as well?

**Comment by alongosz** [comment]
> @alongosz @Steveb-p, so is this 3.3 as well?

The answer to that question is complicated. I'm not 100% sure if we should change the 3.3 doc. In favor of that would be the fact that Platform namespace part is deprecated and doc should refer to the new "code". On the other hand due to BC this exist in "3.3-new" packages so might be confusing. Since the namespace part is deprecated, it falls under BC/FC[1] layer the same way as old eZ namespaces do. It means that new classes in 2.5 and 3.3 packages need to have non-Platform namespace

[1] forward compatibility layer, in 2.5 and 3.3

**Comment by Steveb-p** [comment]
Maybe a note would be in order, that the `Platform` NS part will be removed in 4.0?

Otherwise this will look like an oversight on our part and this question will pop up again.

**Pull request merged**
