### PR TITLE
Fix Aggregation IntegerStatsAggregation example

### PR DESCRIPTION
**Pull request by arfaram**
Add the right Aggregation field class

Provide some getter example

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | 
| Versions      | 3.3+

### CODE REVIEW

**Comment by DominikaK** [comment]
@arfaram, does the added note apply only to this aggregation, or to all Stats aggregations?

**Comment by arfaram** [comment]
> @arfaram, does the added note apply only to this aggregation, or to all Stats aggregations?

@DominikaK Indeed, float and raw stats aggregation have the same statistical information

**Comment by DominikaK** [comment]
How about including the method names in the bullet points in lines 6-10 of this page (and the two other stats-pages), to keep the info in one place?

**Review by adamwojs — APPROVED** [review]

**Comment by DominikaK** [comment]
Replaced by https://github.com/ezsystems/developer-documentation/pull/1518

**Pull request closed without merging**
