### PR TITLE
Fix typo for render_esi

### PR DESCRIPTION
**Pull request by SylvainGuittard**
Thanks @flovntp for reporting this typo 👍

### CODE REVIEW

**Comment by flovntp** [comment]
👍

**Comment by DominikaK** [comment]
@Steveb-p, you recently modified this section, can you confirm?

**Comment by Steveb-p** [comment]
It's not a typo. Referencing controllers using single colon was deprecated in Symfony.

https://symfony.com/blog/new-in-symfony-4-1-deprecated-the-bundle-notation

**Comment by SylvainGuittard** [comment]
Thank @Steveb-p!
Closing :)

**Pull request closed without merging**
