### PR TITLE
EZP-28086: Remove references to viewLocation and viewContent

### PR DESCRIPTION
**Pull request by DominikaK**
| Question      | Answer
| ------------- | ---
| JIRA Ticket   | https://jira.ez.no/browse/EZP-28086
| Versions      | all

TODO:
- [x] Verify https://doc.ezplatform.com/en/2.1/guide/content_rendering/#view92manager-view92provider section

### CODE REVIEW

**Comment by natanael89** [comment]
Looks good. I would also add that you need to provide "contentId" or "locationId" (or both), otherwise it will fail.

**Comment by natanael89** [comment]
I verified "Content and Location view providers" section and made some changes there. Ready for review.

**Comment by DominikaK** [comment]
I can't approve my own PR, but +1 on @natanael89's changes

**Comment by DominikaK** [comment]
@bdunogier, are you OK with the changes now?

**Pull request merged**
