### PR TITLE
Basics -> Supported Response Format

### PR DESCRIPTION
**Pull request by reithor**
"API supports both JSON and XML in terms of response format" seems more approriate,
"response type" or "requested response type" are other options here.

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | 
| Versions      |

### CODE REVIEW

**Comment by andrerom** [comment]
Technically it is both request (in case of body on creation / update of data) and response.

Maybe "accept type", or something, wdyt @bdunogier ?

**Comment by bdunogier** [comment]
Well, "accept type" is a response header in the HTTP domain, so it might be confusing as well... what about "format", or maybe "exchange format" ?

**Comment by bdunogier** [comment]
Well, "accept type" is a response header in the HTTP domain, so it might be confusing as well... what about "format", or maybe "exchange format" ?

**Comment by bdunogier** [comment]
Well, "accept type" is a response header in the HTTP domain, so it might be confusing as well... what about "format", or maybe "exchange format" ?

**Comment by bdunogier** [comment]
Well, "accept type" is a response header in the HTTP domain, so it might be confusing as well... what about "format", or maybe "exchange format" ?

**Comment by DominikaK** [comment]
I'd vote for `format` by itself, seems to be the least confusing option.

**Pull request merged**
