### PR TITLE
EZP-29547: Added examples to UI Guidelines buttons component examples & reviewed icons

### PR DESCRIPTION
**Pull request by inakijv**
| Question      | Answer
| ------------- | ---
| JIRA Ticket   | [EZP-29547](https://jira.ez.no/browse/EZP-29547)
| Versions      | 2.2.2

Most important aspects:
Added examples to UI Guidelines of buttons component:
- Cases added: Set of two buttons (with example of Do & Don't), wide button, Buttons with icons, Buttons in menu bars and Button in tables;

Also reviewed styling of Icons Resource (for design consistency purposes with the other UI Guidelines sections)

There's a current issue with the rendering of icons in buttons resource section.

buttons - ez platform developer documentation
icons - ez platform developer documentation

### CODE REVIEW

**Comment by inakijv** [comment]
@damianz5 Rendering of icons in Buttons sections (same for labels of buttons, in sub-section Buttons in menu bars) is still an issue. Could you take a look at it, please? Thank You!

**Comment by inakijv** [comment]
@damianz5 Updated based on your review.

**Comment by damianz5** [comment]
retested, looks good

**Comment by inakijv** [comment]
@DominikaK a new review is needed here, please.
@dew326 yours is also needed too (new examples added to Buttons component page).

**Pull request merged**
