### PR TITLE
Add instructions on encoding database password

### PR DESCRIPTION
**Pull request by glye**
| Question      | Answer
| ------------- | ---
| JIRA Ticket   | N/A
| Versions      | Seems limited to Symfony 5 (not sure), e.g. DXP v3.3 and v4

Based on this community question: https://ezcommunity.slack.com/archives/C032PD5N9UY/p1651091978286979
we should document that database passwords has certain limitations. I'm following this recommendation: https://github.com/symfony/symfony/issues/35568#issuecomment-792657130
and adding the alternative of simply using chars that require no encoding.

I am not sure if using headers inside the tip box works as intended. Also not sure how much entropy discussion is worthwhile here, we want to keep it short but understandable.

### CODE REVIEW

**Comment by carlosmauri** [comment]
I'm pretty sure this will help/prevent others to spent time debugging the issue.
Thanks for documenting it @glye !

**Comment by DominikaK** [comment]
@glye before proofing: do you think we could move the bulk of the text to https://doc.ibexa.co/en/master/getting_started/troubleshooting, and leave only a mention and link on this page? That would prevent overfilling the install guide with too many "special concerns".

**Comment by glye** [comment]
@DominikaK Sure, that would be fine.

**Review by adamwojs — APPROVED** [review]

**Review by DominikaK — APPROVED** [review]

**Comment by carlosmauri** [comment]
Thanks for the work on this guys 👏

**Pull request merged**
