### PR TITLE
fixed dictionary-entry create/list

### PR DESCRIPTION
**Pull request by reithor**
| Question      | Answer
| ------------- | ---
| JIRA Ticket   | N/A
| Versions      | 3.3+
| Edition       | All

see https://developer.fastly.com/reference/cli/dictionary-entry/

### CODE REVIEW

**Review by vidarl — APPROVED** [review]
Yeah, looks like the `dictionary-item` command was renamed to `dictionary-entry` at some point

**Review by vidarl — CHANGES_REQUESTED** [review]
Target branch should  be 3.3

**Comment by adriendupuis** [comment]
> Target branch should be 3.3

Let it on master, I'll cherry-pick on previous versions

**Review by adriendupuis — APPROVED** [review]
- `dictionary-item` last archived version: https://web.archive.org/web/20230130053840/https://developer.fastly.com/reference/cli/dictionary-item/
- `dictionary-entry` first archived version: https://web.archive.org/web/20230330022820/https://developer.fastly.com/reference/cli/dictionary-entry/

**Review by MagdalenaZuba — APPROVED** [review]

**Pull request merged**
