### PR TITLE
RN link absolutization

### PR DESCRIPTION
**Pull request by dabrt**
| Question      | Answer |
| ------------- | --- |
| JIRA Ticket   | none |
| Versions      |  all |

### CODE REVIEW

**Comment by Steveb-p** [comment]
May I ask why?

This will making working with local documentation build a nightmare, and if I'm not mistaken this will cause docs to keep switching between versions?

**Comment by DominikaK** [comment]
In short: because all release notes are merged to all branches of the doc (it's a business decision), and links from RNs in newer versions are constantly broken, because the relevant page does not exist in that version. For example, Site Factory was released with 3.1, to links from https://doc.ibexa.co/en/2.5/releases/ez_platform_v3.1/#site-factory lead to a 404.

It's a ugly hack, but we couldn't figure out a better one. Other ideas welcome :)

**Comment by DominikaK** [comment]
Side: considering the almost non-existent traffic to old RN pages, we could think of removing everything pre-1.13.

**Review by DominikaK — APPROVED** [review]

**Comment by dabrt** [comment]
> Side: considering the almost non-existent traffic to old RN pages, we could think of removing everything pre-1.13.

We could remove them from 3.x and leave in 1.x and 2.x branches, or, even more aggressively, remove all rns in their respective master branches, which would leave us with a clean slate in 4.x

**Pull request merged**
