### PR TITLE
[1.7] Update PAAS requirement text

### PR DESCRIPTION
**Pull request by andrerom**
| Question      | Answer
| ------------- | ---
| JIRA Ticket   | N/A
| Versions      | 1.7

PR for changes to 1.13+: #456

### CODE REVIEW

**Comment by rolandbenedetti** [comment]
Good for me to change that indeed. I would adjust, few typos:

> _As of v1.13 and higher you have the option to subscribe to [eZ Platform Cloud](https://ez.no/Products/eZ-Platform-Cloud), a PaaS offering officially supported by eZ Systems. For other cloud hosting solutions and on-premise or private cloud hosting, you can refer to the requirements below._

**Comment by DominikaK** [comment]
@andrerom if this note refers to 1.13, do we want to add it to the 1.7 branch?

**Comment by andrerom** [comment]
@DominikaK The point of the comment here is more to make it clear we _don't_ support eZ Platform Cloud on 1.7, while also updating the intro across all branches which is out of date.

**Comment by DominikaK** [comment]
Understood, so I second Roland's improvements, they make the fact that Cloud is not supported in 1.7 a bit clearer.

**Comment by andrerom** [comment]
@DominikaK Sure, but what about suggestion in 1.13 PR comment? (last one has suggestion for both 1.7 and 1.13+)

**Comment by DominikaK** [comment]
@andrerom agree, the version from the other PR is even better. If you're OK with that, we can do if with just that one PR, and introduce the changes between 1.7 and 1.13 while merging?

**Comment by andrerom** [comment]
Agreed

**Pull request closed without merging**
