### PR TITLE
EZP-27719 fixing invalid path in solr instructions

### PR DESCRIPTION
**Pull request by tomaszmadeyski**
It is a fix for https://jira.ez.no/browse/EZP-27719

Using the path which was here before ends up in `Specified configuration directory server/ez/template not found!` while trying to run the command

### CODE REVIEW

**Comment by andrerom** [comment]
Alternative would be to have instructions on changing current working directory, however this is the same used by our docker file for solr, so +1.

**Comment by andrerom** [comment]
@tomaszmadeyski the alternative would make it consistent with the bundle doc btw. So that would be better potentially, see: https://github.com/ezsystems/ezplatform-solr-search-engine/blob/master/README.md

**Comment by tomaszmadeyski** [comment]
@andrerom done in 92e8756

**Comment by andrerom** [comment]
Nice, did you test it as well? ;)

**Comment by tomaszmadeyski** [comment]
> Nice, did you test it as well? ;)

Of course I did 😃

**Comment by andrerom** [comment]
@DominikaK all yours, and I guess it should be applies on 1.7 and up like the other PR.

**Comment by DominikaK** [comment]
Added here: https://github.com/ezsystems/developer-documentation/commit/ed07d419b40818106687789b22397562ef60b04e

**Pull request closed without merging**
