### PR TITLE
Update “Extending Admin UI“ tutorial step titles

### PR DESCRIPTION
**Pull request by adriendupuis**
| Question      | Answer
| ------------- | ---
| JIRA Ticket   | N/A
| Versions      | 3.0 (if not all)

- “Creating a content list” → “Creating a top menu item”

### CODE REVIEW

**Comment by DominikaK** [comment]
@adriendupuis, is this still waiting for some more changes?

**Comment by adriendupuis** [comment]
> @adriendupuis, is this still waiting for some more changes?

@DominikaK I didn't ask for review yet because I have to think more about titles of 3a and 3b that refers to “Content List”.

To only change step 2's title for now, this could be this maybe-too-long title:
- Step 2 - Creating a top menu item: Content List
- Step 3a - Filtering the content list
- Step 3b - Adding Edit button to content list

Actual 3a doesn't detail which feature it will use. Could be something like “Step 3a - Add a content type dropdown menu to filter the content list” but it's way too long.

**Comment by DominikaK** [comment]
@adriendupuis What would you say to:

Step 2 - Creating a menu item
Step 3a - Filtering query results
Step 3b - Adding an edit button

**Comment by adriendupuis** [comment]
> @adriendupuis What would you say to:
> 
> Step 2 - Creating a menu item
> Step 3a - Filtering query results
> Step 3b - Adding an edit button

Thank you @DominikaK for this suggestions.

**Review by DominikaK — APPROVED** [review]

**Pull request merged**
