### PR TITLE
Updated images for the platform beginner tutorial

### PR DESCRIPTION
**Pull request by dabrt**
| Question      | Answer |
| ------------- | ---
| JIRA Ticket   | none |
| Versions      | master, 3.1 |

Updated screenshots for the eZ Platform beginner tutorial

### CODE REVIEW

**Comment by MagdalenaZuba** [comment]
Screenshots with Step 6 in a name should be updated to Step 8.

**Comment by dabrt** [comment]
> Screenshots with Step 6 in a name should be updated to Step 8.

Done, please review.

**Comment by andrerom** [comment]
> `Welcome to eZ Platform 3.1.1` in `bike_tutorial_homepage_install_clean.png`

Didn't hear it from me, but maybe save yourself some future updates and edit the screenshoot to say `x.y.z` (use inspect tool in browser to edit the text) ;)

**Comment by dabrt** [comment]
> > `Welcome to eZ Platform 3.1.1` in `bike_tutorial_homepage_install_clean.png`
> 
> Didn't hear it from me, but maybe save yourself some future updates and edit the screenshoot to say `x.y.z` (use inspect tool in browser to edit the text) ;)

It is there, in writing 8-)))
Thank you for the suggestion. We'll do so starting with the first version after the rebranding.

**Pull request merged**
