### PR TITLE
Fix the parameter name to be able to override.

### PR DESCRIPTION
**Pull request by Plopix**
Thanks @maximstrukov

### CODE REVIEW

**Comment by DominikaK** [comment]
@Plopix, you are correct that currently the parameteres are not provided in practical way, but we should actually change them to be displayed in full (tabbed) yaml format, like we do with other configuration. We'll do that in a separate PR. Thanks for pointing this out.

**Comment by Plopix** [comment]
and we don't warn all the users seeing this up to 2.5.1? we lost half a day on that as it was not obvious at all. Thx!

**Comment by DominikaK** [comment]
@Plopix, here's our proposal, formatted to be easier to use directly in code: https://github.com/ezsystems/developer-documentation/pull/670

**Comment by Plopix** [comment]
is this working? I don't think those is a semantic configuration.

**Comment by adamwojs** [comment]
Hi @Plopix!

Sorry for this inconvenience. 

> is this working? I don't think those is a semantic configuration.

"It's complicated" The semantic configuration is available for:

* Change password  (https://github.com/ezsystems/ezplatform-user/blob/master/src/bundle/DependencyInjection/Configuration/Parser/ChangePassword.php#L24-L40)
* User registration (https://github.com/ezsystems/ezplatform-user/blob/master/src/bundle/DependencyInjection/Configuration/Parser/UserRegistration.php#L32-L42)

Update Form for User Settings is configured using Views: https://github.com/ezsystems/ezplatform-user/pull/21

The semantic configuration is missing for User Settings List, Forgot and Reset Password. 

IMHO something worth to fix in 3.0 in one way or another:
A) providing semantic configuration 
B) using ezdesign 

// cc @mikadamczyk @ViniTou

**Comment by Plopix** [comment]
this is probably why for the time being this pr is valid waiting for the semantic configuration to be done.

just my opinion ;)

**Pull request merged**
