### PR TITLE
Page structure

### PR DESCRIPTION
**Pull request by DominikaK**
Adds mkdocs.yml with very initial config and page structure.

Note: some page names are different than the originals in Confluence and some pages will be combined. Comments show which existing pages should be included in which files.

### CODE REVIEW

**Comment by DominikaK** [comment]
@mere-teresa @kusztel

**Comment by mere-teresa** [comment]
I like this plan, except that some files are missing. When I export from Confluence, I have more files than that, because of Subpages.

**Comment by DominikaK** [comment]
@mere-teresa: which is precisely what my comment referred to:
> some pages will be combined. Comments show which existing pages should be included in which files.

**Comment by mere-teresa** [comment]
https://gist.github.com/mere-teresa/7b950219b6b6d0d87f3acb91ceab863e it's a load of work.

**Pull request merged**
