### PR TITLE
EZP-29234: Simplifying cookbook steps

### PR DESCRIPTION
**Pull request by konradoboza**
JIRA issue: https://jira.ez.no/browse/EZP-29234

This PR contains simplified steps for creating Accept header based REST API response. It is a followup for:
https://github.com/ezsystems/ezpublish-kernel/pull/2434
https://github.com/ezsystems/PlatformUIBundle/pull/986

### CODE REVIEW

**Comment by andrerom** [comment]
NOTE: We should not merge this before 1.13.5 release, as it will not work before then.

**Comment by DominikaK** [comment]
Should this also go to 1.7 and 2.x, like the previous PR?

**Comment by konradoboza** [comment]
This one was merged into 1.13 and higher: https://github.com/ezsystems/developer-documentation/pull/288. It applies also to this one.

**Comment by konradoboza** [comment]
This one should be merged to 1.13 and 2.5 as is, once 1.13.5 is released. For 3.0 paths from https://github.com/ezsystems/developer-documentation/pull/632/files#diff-7eccec79410a7e3c0ef2dee9da63f353 should be applied (either on the fly during merge, or by creating another PR against master). Up to you @DominikaK. 🙂

**Comment by konradoboza** [comment]
I think we can merge this one: https://github.com/ezsystems/ezplatform-ee/releases/tag/v1.13.5.

**Comment by andrerom** [comment]
Indeed, @DominikaK removed the special case label, should be all cleared for merge now afaik.

**Pull request merged**
