### PR TITLE
Fix code snippet in first part of field type tutorial

### PR DESCRIPTION
**Pull request by ghost**
| Question      | Answer
| ------------- | ---
| JIRA Ticket   | 
| Versions      | 4.6, 4.5, 3.3
| Edition       | 

#### Checklist

- [ ] Text renders correctly
- [ ] Text has been checked with vale
- [ ] Description metadata is up to date
- [ ] Redirects cover removed/moved pages
- [ ] Code samples are working
- [ ] PHP code samples have been fixed with PHP CS fixer
- [ ] Added link to this PR in relevant JIRA ticket or code PR

### CODE REVIEW

**Comment by ms2ad** [comment]
Before:
Screenshot 2024-02-14 at 11 32 12


After:
Screenshot 2024-02-14 at 11 35 19

**Review by mnocon — APPROVED** [review]
Thank you for taking time to report and fix these issues! 🙇

**Comment by ms2ad** [comment]
@mnocon Let me misuse this comment section to ask whether it would also be better to be more specific with the template here https://doc.ibexa.co/en/latest/tutorials/generic_field_type/4_introduce_a_template/: i.e. a more explicit path like `templates/themes/standard` (+ another subfolder?) for where to place the template and using `@ibexadesign/` in the JSON config?

I thought about creating a PR for that but was unsure about it.

**Comment by adriendupuis** [comment]
> @mnocon Let me misuse this comment section to ask whether it would also be better to be more specific with the template here https://doc.ibexa.co/en/latest/tutorials/generic_field_type/4_introduce_a_template/: i.e. a more explicit path like `templates/themes/standard` (+ another subfolder?) for where to place the template and using `@ibexadesign/` in the JSON config?
> 
> I thought about creating a PR for that but was unsure about it.

I'm agree with that. Even https://doc.ibexa.co/en/latest/content_management/field_types/form_and_template/#template-variables linked from this page is not clear enough about field block template path (if not worse as it seem to give deprecated bundle path).

I add it to my todo list but, @ms2ad, if you want to open a PR about this issue, please do so.

**Review by adriendupuis — APPROVED** [review]

**Pull request merged**
